packages:
    - '.'

# 依赖分类目录：在 package.json 中用 "catalog:分类名" 引用
catalogs:
    # 项目运行必须的核心依赖
    vue-core:
        vue: ^3.5.24
        vue-router: ^5.0.2

    # 代码质量（类型检查等）
    code-quality:
        vue-tsc: ^3.1.4

    # 构建
    build:
        vite: ^5.4.0
        '@vitejs/plugin-vue': ^6.0.1
        # 检查vite插件（调试工具）
        vite-plugin-inspect: ^0.7.0
        # 优化构建（排除不需要的文件）
        vite-plugin-optimize-exclude: ^0.0.1

    # 工具库（类型、TS、配置、插件等）
    utils:
        '@types/diacritics': ^1.3.3
        '@types/node': ^24.10.1
        '@types/markdown-it-link-attributes': ^3.0.5
        '@vue/tsconfig': ^0.8.1
        typescript: '~5.9.3'
        # 把vue文件转换为路由
        unplugin-vue-router: ^0.19.2
        # 把markdown转换为vue组件
        unplugin-vue-markdown: ^29.2.0
        # 自动导入 API（ref、computed、useRouter 等）
        unplugin-auto-import: ^0.18.0
        # 自动导入组件
        unplugin-vue-components: ^0.27.0
        dayjs: ^1.11.13
        '@unhead/vue': ^2.0.0
        '@vueuse/core': ^14.2.0
        # 给markdown生成目录
        markdown-it-table-of-contents: ^1.1.0
        # 处理非ascii字符
        diacritics: ^1.3.0
        # 给markdown生成锚点
        markdown-it-anchor: ^9.2.0
        shiki: ^3.22.0
        '@shikijs/markdown-it': ^3.22.0
        '@shikijs/transformers': ^3.22.0
        '@shikijs/twoslash': ^3.22.0
        # 给markdown链接添加属性
        markdown-it-link-attributes: ^4.0.1
        # 处理 @user/github 之类的链接
        markdown-it-magic-link: ^0.1.4
        markdown-it-github-mention-card: ^1.0.0
        # 自动导入图标组件
        unplugin-icons: ^23.0.1

    # UI 框架、组件库
    ui-framework: {}

    # 常用组件
    ui-components: {}

    # 样式
    style:
        unocss: ^66.6.0
        '@unocss/reset': ^66.6.0
        '@unocss/preset-icons': ^66.6.0
        '@iconify/json': ^2.2.437

    # 数据处理
    data: {}

    # 测试
    test: {}

    # 文档
    docs: {}

    # 部署
    deploy: {}

    # 其他
    other: {}
